# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: setup
  - init: |
      sudo apt-get -y install git-core gitk git-gui curl lvm2 thin-provisioning-tools python-pkg-resources python3-virtualenv python3-oauth2client xz-utils python3
    command: |
      cd ${GITPOD_REPO_ROOT}
      git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      echo -e 'umask 022\nexport PATH=${GITPOD_REPO_ROOT}/depot_tools:${PATH}' | tee -a ~/.bashrc
      . ~/.bashrc
      mkdir ${GITPOD_REPO_ROOT}/chromiumos
      cd ${GITPOD_REPO_ROOT}/chromiumos
      git config --global color.ui true
      repo init -u https://chromium.googlesource.com/chromiumos/manifest.git --repo-url https://chromium.googlesource.com/external/repo.git -b stable -c --depth=1
      repo sync -j$(($(nproc) + $(($(nproc) / 2)) ))
      cros_sdk

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
